### ISSUE TITLE
PHP 8.2 ready

### ISSUE THREAD

**Issue by daniel-calderini** [diablomedia/zf1-locale#252]
While upgrading to PHP 8.2, I noticed the following in the `composer update` output:

```
- Downgrading diablomedia/zendframework1-locale (1.0.6 => 1.0.5)
```

This seems due to the requirements in https://github.com/diablomedia/zf1-locale/blob/1.0.6/composer.json:

```
"php": "^7.4 || ~8.0.0 || ~8.1.0"
```

Those are not compatible with PHP 8.2, while the requirements in the previous version are https://github.com/diablomedia/zf1-locale/blob/1.0.5/composer.json:

```
"php": "^7.0 || ^8.0",
```

Is it possible to create a new release of this library (and of other `diablomedia/*` libraries) that allow PHP 8.2 ?

**Comment by jaydiablo** [comment]
@daniel-calderini thanks for the nudge, I've cut releases of all of the packages (and the main zf1 one if you use that) that add PHP 8.2 to the allowed PHP versions in composer.json, you should be all set now.
